name: product_app
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  provider: ^6.0.0

  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Uncomment this line to use the flutter_lints package.
  # See https://pub.dev/packages/flutter_lints for more information.
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Alex Andrew ancient camera.jpg
    - assets/brown teddy.jpg
    - assets/Canon camera.jpg
    - assets/Canon movie shooting camera.jpg
    - assets/CBD Lotion.jpg
    - assets/chuck headphone and condenser mic.jpg
    - assets/Fujafilm Camera.jpg
    - assets/furniture.jpg
    - assets/Gigabyte sound box.jpg
    - assets/Go Pro Camera.jpg
    - assets/Guitar pic metal.jpg
    - assets/heavy duty toy vehicle.jpg
    - assets/i phone X.jpg
    - assets/i Watch.jpg
    - assets/K 240 headphones.jpg
    - assets/maria dragon.jpg
    - assets/Michael Kors Watch.jpg
    - assets/Nikon Camera Lense.jpg
    - assets/Nikon Camera.jpg
    - assets/Raspberry pi motherboard.jpg
    - assets/Sony controler.jpg
    - assets/Spark Drone.jpg
    - assets/toy_couple.jpg
    - assets/valeri mak perfume.jpg
    - assets/Venus facial kit.jpg
    - assets/Vit C serum.jpg
    - assets/VR.jpg
    - assets/white teddy.jpg
    - assets/Starting logo.jpg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro-Regular.ttf
  #       - asset: fonts/TrajanPro-Bold.ttf
  #         weight: 700
